version: '3.8'

services:
  webull-bot:
    build: .
    container_name: webull-bot
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: python webull_portfolio_rebalancer_final.py
    restart: unless-stopped

  webull-bot-interactive:
    build: .
    container_name: webull-bot-interactive
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: /bin/bash 